version: '2'

#volumes:
#  nfsgrafana:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=10.0.0.100,rw
#      device: ":/mnt/barracuda/nfsgrafana"
#  nfsprometheus:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=10.0.0.100,rw
#      device: ":/mnt/barracuda/nfsprometheus"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
    - 3000:3000
    volumes:
    - /mnt/nfsgrafana:/var/lib/grafana
    depends_on:
    - prometheus

  prometheus:
    build: ./prometheus
    image: prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
    - 3001:9090
    volumes:
    - /mnt/nfsprometheus:/opt/prometheus/data
    depends_on:
    - cadvisor

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
    - 3002:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
    - 3003:6379
